### ISSUE TITLE
Feature request: Additional delay time after successful wake-up check

### ISSUE THREAD

**Issue by Grandma-Betty** [b-jesch/script.advanced.wol#1]
This is not an issue but a "cosmetical" feature request or moreover an improvement. I hope you don't mind I write this down here on GitHub.

When the target device to be woken up (in my cas a Synology NAS) by the Advanced Wake On Lan add-on, it gets checked by ping commands whether the device is ready or not.
This is working very well but a successful ping response is just indicating that the NIC of the target device is up and running. But most other services (e.g. SMB) are not up and running yet at the moment when the NIC is ready. Instead, in my case, those services can take up between 10 and 15 seconds longer than the NIC interface itself to startup. This ends up in annoying error messages when trying to access the target device's SMB shares too early.

So the feature request would be to add an optional delay time after a successful ping response before the target device is being reported back as woken up successfully.

Thank you for considering about that feature which would save me a lot of nerves.

**Comment by b-jesch** [comment]
I've just implemented a message delay for the host up notification. I think that suits your wish. You'll find this option in the advanced settings section.

Feel free to update this addon from the german "Nerdsrepo": https://repo.kodinerds.net
