### ISSUE TITLE
strings.po addon.xml ita

### ISSUE THREAD

**Issue by Renato-4132** [b-jesch/script.advanced.wol#4]
[wol kodi.zip](https://github.com/b-jesch/script.advanced.wol/files/14293811/wol.kodi.zip)
some changes on language addon.xml and strings.po
p.s works on kodi nexus latest version. could be pushed up to the main repo kodi 
thanks

**Comment by b-jesch** [comment]
Please note, that the language file inside the zip has a wrong structure. Use this file https://github.com/b-jesch/script.advanced.wol/blob/Matrix_NG/resources/language/resource.language.it_it/strings.po as template and adapt your changes. Modifications in addon.xml can be done by me.

Thank you.

**Comment by Renato-4132** [comment]
Ok got it ! wrong template fixed
[strings.po.zip](https://github.com/b-jesch/script.advanced.wol/files/14294149/strings.po.zip)

**Comment by b-jesch** [comment]
Merged.
