### ISSUE TITLE
ping notify

### ISSUE THREAD

**Issue by Renato-4132** [b-jesch/script.advanced.wol#5]
Little bug, or my mistake
when server is active ,the remote libreelec sends wol command on startup and the notify say server is up,server active.
after that the notification pops and counts 20 secs and says again server up with same notification.
the question is: if it allready said that the server is up, why count again and notify a second time ?

**Comment by b-jesch** [comment]
There is a difference between the response of a ping - that means the network configuration is responsible and ready - and the complete functionality of a NAS. NAS needs additional time to initialize their storage, often about 120-300 secs - for this is the additional delay. If you don't want to see this message, set the delay to 0.

**Comment by Renato-4132** [comment]
Hi, You can't set to 0. jumps 10 20 30 40 and so on. maybe nas ping settings and normal ping for server can be disjoined in two separate options. Just asking ...

**Comment by b-jesch** [comment]
Since yesterday...

![Bildschirmfoto von 2024-02-17 11-05-18](https://github.com/b-jesch/script.advanced.wol/assets/10152384/4ef285d8-0507-4e38-8c38-052d0b404ba1)

**Comment by Renato-4132** [comment]
Really Strange .
Tested now but value jumps 10 20 30
I removed it and reinstalled, but same problem.
Maybe nexus fault ? i dont think so and version says 4.0.5 matrix
i downloaded the zip file from github, i could not install it by repository because it's for matrix not for nexus.
any idea ?

**Comment by Renato-4132** [comment]
downloaded again now works !
maybe some changed in the code i saw 19 hours ago....., but works like a charm now !

**Comment by b-jesch** [comment]
The Matrix version is upwards compatible to Nexus and Omega (same ABI).
