### ISSUE TITLE
keep Nas or server wake

### ISSUE THREAD

**Issue by Renato-4132** [b-jesch/script.advanced.wol#6]
Hi, thanks for keeping the project alive before all !
Question. 
If I need to keep a server or Nas awake is it possible to send wol signal every x time ? 
Maybe a menu with a bunch of settings that will do the job ?

**Comment by b-jesch** [comment]
Sending WOL packets to a device that is already alive has no effect. See here: https://forum.kodi.tv/showthread.php?tid=121142&pid=3183388#pid3183388 and here: https://forum.kodi.tv/showthread.php?tid=121142&pid=3193987#pid3193987

**Comment by Renato-4132** [comment]
Thanks for the answer...
The workaround will be sending a ping from a raspberry and waking up the server if kodi is online. Quit easy to solve 👍

**Comment by b-jesch** [comment]
Monitoring network traffic and shutdown the server when no or minimal traffic appars should be the task for your NAS. There are several solutions : https://askubuntu.com/questions/105536/tool-to-shutdown-system-when-there-is-no-network-traffic

**Comment by Renato-4132** [comment]
Nice to see you spent some time for this ,
But I already did my own coding...monitors traffic,disk usage , printer online, and human presence at PC , also when the server goes online sends clean and scan video library.
That will prevent scans while server is offline and cleaning all Kodi library to 0. 
Also pings the remote libreelec , and if online Will not power down the server...
Only matter if you reset libreelec.. will power down quickly and not coming up in time..
Will just have to copy a bit of the code and paste it inside the raspberry.
No matter... Can be done quit simple , but if the wake on lan  was continued while libreelec is online would be a simple way... Anyway.. a workaround can be done. That is the only way I guess...thanks a lot for all !
